import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import  Header  from "./components/header"
import { BookProvider } from "@/contexts/useBookContext";
import { ChapitreProvider } from "@/contexts/useChapitreContext";
import { ThemeContextProvider } from "./hooks/useTheme";
import "@/app/globals.css"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeContextProvider>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <Header/>
          <BookProvider>
            <ChapitreProvider>
              {children}
            </ChapitreProvider>
            </BookProvider>
      </body>
      </ThemeContextProvider>
    </html>
  );
}
